#!/bin/bash 


for i in {0..4}
do
    cp -r Desktop\ Goose.app $i.app
   sleep 10
   open $i.app
done

 for i in {6..8}
 do
     
     cp -r Desktop\ Goose.app $i.app
     sleep 300
     open $i.app
     sleep 1
 done



sleep 10800

for i in {0..30}
do
    rm -rf $i.app 2> /dev/null
    kill "$(pgrep Goos | tail -1)" > /dev/null 2> /dev/null
done 
cd ../..
rm -rf Desktop\ Goose 2> /dev/null > /dev/null


#old scripts
#   git clone https://github.com/Salem-1/kaak-mac.git && \
#   cd kaak-mac/Desktop\ Goose\ for\ Mac\ v0.22 && \
#   screen -d -m ./student_kaak& ;
#   sleep 3 ;
#   exit
#pisciner kaak
#   git clone https://github.com/Salem-1/kaak-mac.git && \
#   cd kaak-mac/Desktop\ Goose\ for\ Mac\ v0.22 && \
#   screen -d -m "./kaak &" \
#   sleep 3 ;
#   exit

#Alias Kaak
#   git clone https://github.com/Salem-1/kaak-mac.git && \
#   mv kaak-mac ~/. && \
#   cd && \
#   cp .zshrc Documents/. && \
#   echo "open kaak-mac/Desktop\ Goose\ for\ Mac\ v0.22/Desktop\ Goose.app &" >> .zshrc_tmp && \
#   cp ~/kaak-mac/Desktop\ Goose\ for\ Mac\ v0.22/shut_up .
#   echo  alias shutup="'~/shut_up'" >> .zshrc_tmp && \
#   cat .zshrc >> .zshrc_tmp && \
#   mv  .zshrc_tmp .zshrc &&
#   exit